'use strict';

/**
 * Token Service — JWT Lifecycle Management
 *
 * Handles all JWT operations:
 *   - Signing access tokens (with jti for blocklist support)
 *   - Setting and clearing HTTP-only session cookies
 *   - Verifying tokens
 *   - Building the JWT payload per FRD Section 8.2
 *
 * FRD Section 8.2:
 *   "Sessions are managed via HTTP-only cookies containing a signed JWT."
 *   "JWT payload must contain: account ID, email, role, and expiry timestamp."
 *
 * HTTP-ONLY COOKIES:
 *   The cookie is set with httpOnly: true, which prevents JavaScript
 *   from reading it (protects against XSS). sameSite: 'strict' prevents
 *   CSRF attacks. secure: true (production only) ensures HTTPS delivery.
 *
 * JTI (JWT ID):
 *   Every token includes a unique jti claim generated by crypto.randomUUID().
 *   This enables the TokenBlocklist to invalidate specific tokens on logout
 *   without invalidating all tokens for that account.
 */

import jwt from 'jsonwebtoken';
import { generateJti } from '../helpers/tokenGenerator.helper.js';
import { AUTH } from '../config/constants.js';
import { SESSION_COOKIE_NAME } from '../middleware/auth.middleware.js';

// ─────────────────────────────────────────────────────────────────────
// JWT CONFIGURATION
// ─────────────────────────────────────────────────────────────────────
const JWT_SECRET     = () => process.env.JWT_SECRET;
const JWT_EXPIRES_IN = () => process.env.JWT_EXPIRES_IN || '1h';

/**
 * Sign a JWT access token for an authenticated admin account.
 *
 * @param {Object} account - The authenticated Account document
 * @returns {{ token: string, jti: string, expiresAt: Date }}
 */
const signAccessToken = (account) => {
  const jti = generateJti();

  const token = jwt.sign(
    {
      // FRD Section 8.2 required payload fields:
      id:    account._id,
      email: account.email,
      role:  account.role,
      // Additional fields:
      jti,   // For TokenBlocklist support on logout
    },
    JWT_SECRET(),
    { expiresIn: JWT_EXPIRES_IN() }
  );

  // Decode to get the exact expiry timestamp (for blocklist TTL)
  const decoded = jwt.decode(token);
  const expiresAt = new Date(decoded.exp * 1000);

  return { token, jti, expiresAt };
};

/**
 * Verify and decode a JWT token.
 * Throws JsonWebTokenError or TokenExpiredError on failure
 * (caught by auth.middleware.js and errorHandler).
 *
 * @param {string} token
 * @returns {Object} Decoded JWT payload
 */
const verifyToken = (token) => {
  return jwt.verify(token, JWT_SECRET());
};

/**
 * Build the cookie options object for the session cookie.
 * Options differ between development and production for security.
 *
 * @param {Date} expiresAt - The JWT's expiry date
 * @returns {Object} Express cookie options
 */
const getCookieOptions = (expiresAt) => ({
  httpOnly: true,  // Not accessible via document.cookie (prevents XSS theft)
  expires:  expiresAt,
  sameSite: process.env.NODE_ENV === 'production' ? 'strict' : 'lax',
  // secure: true enforces HTTPS-only. Off in development for http://localhost.
  secure: process.env.NODE_ENV === 'production',
  path: '/',
});

/**
 * Set the session cookie on the response.
 * Called after successful login.
 *
 * @param {import('express').Response} res
 * @param {string} token - The signed JWT string
 * @param {Date} expiresAt - When the cookie should expire
 */
const setSessionCookie = (res, token, expiresAt) => {
  res.cookie(SESSION_COOKIE_NAME, token, getCookieOptions(expiresAt));
};

/**
 * Clear the session cookie from the response.
 * Called on logout. Ensures the cookie is removed from the browser.
 *
 * @param {import('express').Response} res
 */
const clearSessionCookie = (res) => {
  res.cookie(SESSION_COOKIE_NAME, '', {
    httpOnly: true,
    expires: new Date(0), // Set expiry to epoch — browser deletes immediately
    sameSite: process.env.NODE_ENV === 'production' ? 'strict' : 'lax',
    secure: process.env.NODE_ENV === 'production',
    path: '/',
  });
};

export {
  signAccessToken,
  verifyToken,
  getCookieOptions,
  setSessionCookie,
  clearSessionCookie,
};